### ISSUE TITLE
📖 Docs: Readesign Documentation

### ISSUE THREAD

**Issue by N3v1** [ify47/Age-Calculator-App#1]
Hi @ify47 👋, 
Perhaps I can assist you in redesigning your README.md file.

Best regards
NH

**Comment by ify47** [comment]
Sure, thanks. @N3v1

**Comment by N3v1** [comment]
Hi @ify47 👋, 
do you have a logo or something like that for your Website/App?

Thank you kindly 🙏
Best regards
NH

**Comment by ify47** [comment]
No, i don't

**Comment by ify47** [comment]
Thank you for the redesign  🙏
